language: csharp
solution: AdvanceDLSupport.sln

os:
  - linux
  - osx

env:
  - BuildConfiguration=Debug TargetPlatform=x86
  - BuildConfiguration=Release TargetPlatform=x86
  - BuildConfiguration=Debug TargetPlatform=x64
  - BuildConfiguration=Release TargetPlatform=x64
  - BuildConfiguration=Debug TargetPlatform="Any CPU"
  - BuildConfiguration=Release TargetPlatform="Any CPU"

addons:
  apt:
    packages:
      - gcc-multilib

mono: latest
dotnet: 2.1.3

before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - chmod +x scripts/*

install:
  - dotnet restore

script: ./scripts/travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
