language: csharp
solution: AdvanceDLSupport.sln

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gcc-multilib

mono: latest
dotnet: 2.1.3

before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - chmod +x scripts/*

install:
  - dotnet restore

script: ./scripts/travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
