language: csharp
solution: AdvanceDLSupport.sln

os:
  - linux
  - osx

env:
  - Configuration=Debug Platform=x86
  - Configuration=Release Platform=x86
  - Configuration=Debug Platform=x64
  - Configuration=Release Platform=x64
  - Configuration=Debug Platform="Any CPU"
  - Configuration=Release Platform="Any CPU"

addons:
  apt:
    packages:
      - gcc-multilib

mono: latest
dotnet: 2.1.3

before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - chmod +x scripts/*
  - echo $Platform

install:
  - curl https://dot.net/v1/dotnet-install.sh -o ~/dotnet-install.sh && chmod +x ~/dotnet-install.sh
  - ~/dotnet-install.sh --channel Current --install-dir ~/dotnet-32 --architecture x86 --no-path
  - dotnet restore

script:
  - ./scripts/travis-build.sh
  - ./scripts/travis-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
