language: csharp
solution: AdvanceDLSupport.sln

os:
  - linux
  - osx

env:
  # - Configuration=Debug Platform=x86
  # - Configuration=Release Platform=x86
  - Configuration=Debug Platform=x64
  - Configuration=Release Platform=x64
  - Configuration=Debug
  - Configuration=Release

addons:
  apt:
    packages:
      - gcc-multilib

mono: preview
dotnet: 2.1.3

before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - chmod +x scripts/*
  - echo $Platform

install:
  - curl https://codecov.io/bash --output outcov.sh --retry 10 --retry-delay 3
  - dotnet restore

script:
  - ./scripts/travis-build.sh
  - ./scripts/travis-coverage.sh

after_success:
  - bash "codecov.sh"
