image: Visual Studio 2019
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh -MaximumRetryCount 10 -RetryIntervalSec 3

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

install:
  - ps: .\scripts\appveyor-install-dotnet-32.ps1

before_build:
  - dotnet restore
build:
  parallel: false
  project: AdvanceDLSupport.sln

test_script:
  - ps: .\scripts\appveyor-coverage.ps1

after_test:
  - ps: |
      $env:PATH = '/bin;/usr/bin;/usr/local/bin;C:\msys64\usr\bin;' + $env:PATH
      bash "codecov.sh"