image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile C:\dotnet-install.ps1
  - ps: C:\dotnet-install.ps1 -Channel Current -InstallDir "C:\Program Files (x86)\dotnet" -Architecture x86 -NoPath

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln

test_script: scripts\appveyor-coverage.bat

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
