image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1
  - ps: dotnet-install.ps1 -Architecture x86 -NoPath

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln

test_script: scripts\appveyor-test.bat

after_test:
  - cmd: scripts\appveyor-coverage.bat
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
