image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln
test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll

after_test:
  - nuget install altcover -OutputDirectory altcover -Version 1.6.230
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration Debug -- -i=AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0 -o=instrumented -x=coverage.xml --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+
  - copy /y instrumented\* AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "AdvancedDLSupport.Tests\bin\Debug\netcoreapp2.0" -- test AdvancedDLSupport.Tests --no-build
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "Mono.DllMap.Tests\bin\Debug\netcoreapp2.0" -- test Mono.DllMap.Tests --no-build