image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"

configuration:
  - Debug
  - Release

environment:
  matrix:
    - platform: x86
      output_dir: x86\%CONFIGURATION%
    - platform: x64
      output_dir: x64\%CONFIGURATION%
    - platform: Any CPU
      output_dir: \%CONFIGURATION%

before_build:
  - dotnet restore

build:
  parallel: true
  project: AdvanceDLSupport.sln

test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll

after_test:
  - dotnet test --no-build
  - nuget install altcover -OutputDirectory altcover -Version 1.6.230
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% -- -i=AdvancedDLSupport.Tests\bin\%output_dir%\netcoreapp2.0 -o=instrumented-adl -x=coverage-adl.xml --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+ --assemblyExcludeFilter=Mono\.DllMap.+
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --configuration %CONFIGURATION% -- -i=Mono.DllMap.Tests\bin\%output_dir%\netcoreapp2.0 -o=instrumented-mdl -x=coverage-mdl.xml --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+
  - copy /y instrumented-adl\* AdvancedDLSupport.Tests\bin\%output_dir%\netcoreapp2.0
  - copy /y instrumented-mdl\* Mono.DllMap.Tests\bin\%output_dir%\netcoreapp2.0
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "AdvancedDLSupport.Tests\bin\%output_dir%\netcoreapp2.0" -- test AdvancedDLSupport.Tests --no-build
  - dotnet run --project altcover\altcover.1.6.230\tools\netcoreapp2.0\AltCover\altcover.core.fsproj --no-build -- runner -x "dotnet" -r "Mono.DllMap.Tests\bin\%output_dir%\netcoreapp2.0" -- test Mono.DllMap.Tests --no-build
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh